from .target_columns import (
    check_ctl_action,
    check_ctl_loading,
    check_ctl_validfrom,
    check_dimension_name,
    check_duplicate_columns,
    check_duplicate_stream_names,
    check_end_dttm_pk_requires_start,
    check_fact_aggregate_name,
    check_fact_aggregate_report_dt,
    check_history_pair,
    check_history_types,
    check_pk_values,
    check_partition_columns,
    check_reference_pk_count,
    check_reference_row_hash,
    check_required_columns,
    check_required_values,
    check_table_has_pk,
)


CHECKS = [
    check_required_columns,
    check_required_values,
    check_duplicate_columns,
    check_duplicate_stream_names,
    check_pk_values,
    check_table_has_pk,
    check_end_dttm_pk_requires_start,
    check_partition_columns,
    check_history_pair,
    check_fact_aggregate_report_dt,
    check_fact_aggregate_name,
    check_dimension_name,
    check_reference_row_hash,
    check_reference_pk_count,
    check_history_types,
    check_ctl_validfrom,
    check_ctl_action,
    check_ctl_loading,
]
